# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("登录测试")
        .variables(**{"p_username": "test200", "p_password": 123123})
        .base_url("http://123.56.231.107:8000")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("登录测试用例")
            .post("/api/register/")
            .with_headers(
                **{
                    "Content-Type": "application/json",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_json(
                {
                    "account": "$p_username",
                    "email": "$p_username@123.com",
                    "password": "$p_password",
                    "repassword": "$p_password",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
