# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\login_1.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin1(HttpRunner):

    config = (
        Config("登录后关联参数，添加银行卡")
        .variables(**{"p_username": "test11", "p_password": "test11"})
        .base_url("http://localhost:8000")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("登录测试用例")
            .post("/api/v1/login/")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"username": "test11", "password": "test11"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "登录成功")
        ),
        Step(
            RunRequest("添加卡信息关联token")
            .post("/cards/")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "Token $token"}
            )
            .with_json({"card_id": "test11", "card_user": "test11"})
            .validate()
            .assert_equal("status_code", 201)
            .assert_equal("body.card_id", "test11")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin1().test_start()
