# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\regsiter.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
#导入包

class TestCaseRegsiter(HttpRunner):

    # 配置
    config = (
        Config("登录关联") #对应yaml中name，之后的关键字需要加点
        #base_url
        .base_url("http://localhost:8000")
        #参数
        .variables(
            **{
                "a": "1",
                "b": "2"
            }
        )
        .verify(False)
    )
    # 测试步骤
    teststeps = [
        Step(
            RunRequest("登录")# 名称
            .post("/api/v1/login/") #方法
            # header
            .with_headers(
                **{
                    "Content-Type": "application/json",
                }
            )
            # 参数
            .with_json(
                {
                    "username": "test11",
		            "password": "test11"
                }
            )
            .extract()
            .with_jmespath("body.token",'token')
            #断言
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRegsiter().test_start()
