# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\regsiter.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegsiter(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/register/")
            .post("http://123.56.231.107:8000/api/register/")
            .with_headers(
                **{
                    "Content-Type": "application/json",
                    "X-Requested-With": "XMLHttpRequest",
                }
            )
            .with_json(
                {
                    "account": "test177",
                    "email": "test1775@123.com",
                    "password": "123123",
                    "repassword": "123123",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseRegsiter().test_start()
